import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App (TypeScript + Tailwind CSS)",
  description: "Generated by create next app",
};
const poppins = Inter({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "700"]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`)}
      >
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
